adding widget
eduNEXT/edx-analytics-dashboard pull request #6
Opened 2021-08-10 21:10 UTC by tatianatorog

In this pr the help widget was added and the header help link was hidden

![Screenshot from 2021-08-10 16-09-37](https://user-images.githubusercontent.com/66017940/128935478-e45b871a-8c8e-40a2-b95d-6c47c356b798.png)

Stage: https://insights.je.edunextstage.net/

2021-08-11 09:31 UTC, andrey-canon requested changes

2021-08-11 09:31 UTC, andrey-canon commented on analytics_dashboard/templates/help_widget.html
> +</script>
it's missing a line at the end

2021-08-11 09:31 UTC, andrey-canon commented on analytics_dashboard/templates/help_widget.html
> +        widget.style.display = "block";
could you use fade in and fade out ?

2021-08-11 20:00 UTC, magajh commented on analytics_dashboard/templates/help_widget.html
> +        Copyright © 2021 eduNEXT, All rights reserved.
@tatianatorog please add the same method that's in the Ecommerce widget, so that we always show the current year
 https://bitbucket.org/edunext/ecommerce-themes/src/c41d31e86466127d612a84bf5105bb9d6a56c8e8/delling/templates/widgets/help-sidebar.html#lines-71

2021-08-12 02:56 UTC, tatianatorog commented on analytics_dashboard/templates/help_widget.html
> +        widget.style.display = "block";
Yes, it could be used, but we will depend on the jquery library, for something very simple. So I think it is better to leave it in pure js.

2021-08-12 03:29 UTC, tatianatorog commented on analytics_dashboard/templates/help_widget.html
> +        Copyright © 2021 eduNEXT, All rights reserved.
Muchas gracias Maga , ya lo corregí

2021-08-12 12:26 UTC, magajh commented
@tatianatorog se puede probar en stage?

2021-08-12 12:28 UTC, magajh approved these changes

2021-08-12 12:35 UTC, mariajgrimaldi approved these changes

2021-08-12 12:38 UTC, magajh commented
@tatianatorog I was checking this in stage and it looks very good! I think the only thing that is missing is a line break between _privacy policy_ and _Copyright_ 
![tatiana-stage](https://user-images.githubusercontent.com/35777155/129198072-bf35421d-8ab0-44f7-ac79-0e94d433597f.png)

2021-08-12 16:28 UTC, merged